[Bugfix] GitHub actions 오류 해결 (#3)
* fix: requirements path

* fix: status update file name

diff --git a/.github/workflows/crawl.yml b/.github/workflows/crawl.yml
--- a/.github/workflows/crawl.yml
+++ b/.github/workflows/crawl.yml
@@ -18,10 +18,10 @@ jobs:
           cache: "pip" 
 
       - name: Install dependencies
-        run: pip install -r requirements.txt
+        run: pip install -r tasks/requirements.txt
 
       - name: Run crawler
         env:
           REDIS_URL: ${{ secrets.REDIS_URL }}
         run: |
-          python tasks/status_checker.py || echo "⚠️ Script failed, skipping..."
+          python tasks/status_update.py || echo "⚠️ Script failed, skipping..."
